-- Tạo cơ sở dữ liệu
CREATE DATABASE IF NOT EXISTS QLBANHANG;
USE QLBANHANG;

-- Bảng KHACHHANG
CREATE TABLE KHACHHANG (
    MAKH CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR(40) NOT NULL,
    DCHI VARCHAR(50),
    SODT VARCHAR(20),
    NGSINH DATETIME,
    NGDK DATETIME,
    DOANHSO DECIMAL(15,2)
);

-- Bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANV CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR(40) NOT NULL,
    SODT VARCHAR(20),
    NGVL DATETIME
);

-- Bảng SANPHAM
CREATE TABLE SANPHAM (
    MASP CHAR(4) PRIMARY KEY,
    TENSP VARCHAR(40) NOT NULL,
    DVT VARCHAR(20),
    NUOCSX VARCHAR(40),
    GIA DECIMAL(15,2)
);

-- Bảng HOADON
CREATE TABLE HOADON (
    SOHD INT PRIMARY KEY,
    NGHD DATETIME,
    MAKH CHAR(4),
    MANV CHAR(4),
    TRIGIA DECIMAL(15,2),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Bảng CTHD (Chi tiết hóa đơn)
CREATE TABLE CTHD (
    SOHD INT,
    MASP CHAR(4),
    SL INT,
    PRIMARY KEY (SOHD, MASP),
    FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);
